# https://github.com/codecov/example-go
language: go

go:
  - 1.6
  - tip

before_install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/kisielk/errcheck
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/gordonklaus/ineffassign
..- go get -u github.com/client9/misspell/cmd/misspell

install:
  - go get -t -v ./...

script:
  - go build -v ./...
  - go vet ./...
  - go tool vet -shadow=true ./
  - golint ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - errcheck ./...
  - gocyclo -over 15 .
  - ineffassign .
  - misspell ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)