# https://github.com/codecov/example-go
language: go

go:
  - 1.6
  - tip

before_install:
  - go get -t -v ./...
  - go get github.com/golang/lint/golint

script:
  - go vet .
  - golint .
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)